name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  sast:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
         args: -fmt=json -out=results.json ./...
  build and deploy:
    runs-on: ubuntu-latest
    needs: sast
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Build
        run: go build -v ./...
      - name: Deploy a Cloud Function
        id: deploy-function
        uses: google-github-actions/deploy-cloud-functions@v0.1.0
        with:
          name: Rules from BCN Chile
          runtime: go116
          project: ${{ secrets.gcp_project }}
          credentials: ${{ secrets.gcp_credentials }}
